version: "3.9"

services:
  nginx:
    image: nginx:alpine
    network_mode: host
    ports:
      - 9000:9000
    volumes:
      - ./logs:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./secrets:/app/secrets
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 150M
